feat(ci): implement automated workflows and code coverage reporting

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -11,9 +11,9 @@ if ! dart format --output=none --set-exit-if-changed .; then
 fi
 
 # Check analysis
-echo "🕵️ Running dart analyze..."
-if ! dart analyze .; then
-  echo "❌ Error: dart analyze found issues."
+echo "🕵️ Running flutter analyze..."
+if ! flutter analyze .; then
+  echo "❌ Error: flutter analyze found issues."
   exit 1
 fi
 
